---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-website
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
---
apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: example-website1
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples1
  providesApis: [example-grpc-api]
  projectInfo:
    modality: "MR"
    bodyParts: "HEAD"
    processingPurpose: "NA"
    protocol: "HTTP"
    algorithmType: "C"
    packageType: "PK"
    supportedOs: "LI"
    sourceCodeLanguage: "CPP"
    developmentStatus: "OPEN"
---
apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: example-website2
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples2
  providesApis: [example-grpc-api]
  projectInfo:
    modality: "UL"
    bodyParts: "HEAD"
    processingPurpose: "NA"
    protocol: "HTTP"
    algorithmType: "C"
    packageType: "PK"
    supportedOs: "WIN"
    sourceCodeLanguage: "C#"
    developmentStatus: "OPEN"
---
apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: example-website3
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples3
  providesApis: [example-grpc-api]
  projectInfo:
    modality: "MR"
    bodyParts: "HEAD"
    processingPurpose: "NA"
    protocol: "HTTP"
    algorithmType: "C"
    packageType: "PK"
    supportedOs: "WIN"
    sourceCodeLanguage: "C"
    developmentStatus: "OPEN"
---
apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: example-website4
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples4
  providesApis: [example-grpc-api]
  projectInfo:
    modality: "CT"
    bodyParts: "HEAD"
    processingPurpose: "NA"
    protocol: "HTTP"
    algorithmType: "C"
    packageType: "PK"
    supportedOs: "WIN"
    sourceCodeLanguage: "C"
    developmentStatus: "OPEN"
---
apiVersion: backstage.io/v1alpha1
kind: Product
metadata:
  name: example-website5
spec:
  type: website
  lifecycle: experimental
  owner: guests
  system: examples5
  providesApis: [example-grpc-api]
  projectInfo:
    modality: "NM"
    bodyParts: "HEAD"
    processingPurpose: "NA"
    protocol: "HTTP"
    algorithmType: "C"
    packageType: "PK"
    supportedOs: "WIN"
    sourceCodeLanguage: "C"
    developmentStatus: "OPEN"
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-grpc-api
spec:
  type: grpc
  lifecycle: experimental
  owner: guests
  system: examples
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };
